name: GeckoLib
main: gecko10000.geckolib.GeckoLib
version: 0.1
api-version: 1.13
depend:
  - RedLib
libraries:
  - "org.jetbrains.kotlin:kotlin-stdlib:2.0.21"
  # The following seem to not work, likely because
  # they're doing some fancy stuff to the code.
  # - "io.insert-koin:koin-core:3.5.3"
  # - "org.jetbrains.kotlinx:kotlinx-serialization-json:1.6.3"
  # - "com.charleskorn.kaml:kaml:0.67.0"
